Resources:
  ElasticsearchSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Elasticsearch Security Group"
      SecurityGroupEgress:
        - Description: "deny all outbound"
          IpProtocol: "-1"
          CidrIp: "127.0.0.1/32"
      SecurityGroupIngress:
        - Description: "permit Elasticsearch (5432) from AppSecurityGroup"
          FromPort: 443
          IpProtocol: tcp
          SourceSecurityGroupId: !GetAtt AppSecurityGroup.GroupId
          ToPort: 443
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", elasticsearch]]
      VpcId: !Ref VPC
  PokeElasticsearchDomain:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      DomainName: ${self:custom.databaseName}
      ElasticsearchVersion:
      ElasticsearchClusterConfig:
        InstanceCount: "1"
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: "0"
        VolumeSize: "10"
        VolumeType: "standard"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Deny
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "*"
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: true
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", elasticsearch]]
      VPCOptions:
        SubnetIds:
          - Ref: DBSubnet1
          - Ref: DBSubnet2
        SecurityGroupIds:
            - Ref: ElasticsearchSecurityGroup
