version: "3"

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ashketchum
      POSTGRES_PASSWORD: squirtle123
      POSTGRES_DB: pokeshop
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 5s
      retries: 60
  cache:
    image: redis:6
    ports:
      - 6379:6379
    networks:
      - local
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1s
      timeout: 3s
      retries: 60
  queue:
    image: rmohr/activemq:5.10.0
    ports:
      - 61613:61613
      - 8161:8161
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8161"]
      interval: 1s
      timeout: 1s
      retries: 60
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - local
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:16686"]
      interval: 1s
      timeout: 3s
      retries: 60

  api:
    build:
      context: .
    environment:
      REDIS_URL: cache
      DATABASE_URL: postgresql://ashketchum:squirtle123@db:5432/pokeshop?schema=public
      ACTIVEMQ_HOST: queue
      POKE_API_BASE_URL: https://pokeapi.co/api/v2
      JAEGER_HOST: jaeger
      JAEGER_PORT: 9411
    ports:
      - 3000:3000
    networks:
      - local
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      queue:
        condition: service_healthy
      jaeger:
        condition: service_healthy

networks:
  local: